apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: python-web-app-monitor
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: python-web-app
  endpoints:
  - port: http
    path: /metrics
    interval: 15s