apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: python-web-app
  namespace: argocd
spec:
  project: default

  source:
    repoURL: REPO_URL_PLACEHOLDER
    targetRevision: k8s/deploy-monitoring-with-argocd
    path: kubernetes/application/
  destination: 
    server: https://kubernetes.default.svc
    namespace: python-web-app
  syncPolicy:
    syncOptions: 
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true