name: Deploy AWS infrastructure
on:
  push:
    branches:
      - main
  workflow_call:
    
permissions:
  id-token: write
  contents: read

jobs:
  terragrunt_plan:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ vars.AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Terragrunt
        run: |
          curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.1/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt Init VPC
        run: |
          cd infrastructure/dev/vpc
          terragrunt init

      - name: Terragrunt Plan VPC
        run: |
          cd infrastructure/dev/vpc
          terragrunt plan
        
      - name: Terragrunt Apply VPC
        run: |
          cd infrastructure/dev/vpc
          terragrunt apply -auto-approve

      - name: Terragrunt Init EKS
        run: |
          cd infrastructure/dev/eks
          terragrunt init

      - name: Terragrunt Plan EKS
        run: |
          cd infrastructure/dev/eks
          terragrunt plan
          
      - name: Terragrunt Apply EKS
        run: |
          cd infrastructure/dev/eks
          terragrunt apply -auto-approve
      
      
