name: Deploy AWS infrastructure
on:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  deploy_infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      # - name: Configure Git to use GITHUB_TOKEN for module access
      #   env:
      #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     # git config --global url."https://Bartosz-Szadkowski:${{ secrets.MODULES_REPO_TOKEN }}@github.com/".insteadOf "https://github.com/"
      #     git config --global url."https://oauth2:$GH_TOKEN@github.com/Bartosz-Szadkowski/terraform-modules.git".insteadOf "ssh://git@github.com/Bartosz-Szadkowski/terraform-modules.git"


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ vars.AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: init_token
        id: init
        run: |
          git config --global url."https://oauth2:${{ secrets.MODULES_REPO_TOKEN }}@github.com".insteadOf ssh://git@github.com

      - name: Install Terragrunt
        run: |
          curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.1/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Terragrunt Plan 
        run : |
          cd infrastructure/ 
          terragrunt run-all plan 
      
      - name: Terragrunt Apply 
        run: | 
          cd infrastructure/
          terragrunt run-all apply -auto-approve --terragrunt-non-interactive 

