name: Deploy AWS infrastructure
on:
  push:
    branches:
      - main
  workflow_call:
    
permissions:
  id-token: write
  contents: read

jobs:
  terragrunt_plan:
    name: Terragrunt Plan
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ vars.AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Install Terragrunt
        run: |
          curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.1/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Create and Run S3 and DynamoDB setup script
        run: |
          echo "${{ secrets.CREATE_S3_AND_DYNAMODB_SH }}" > ./create_s3_and_dynamodb.sh
          chmod +x ./create_s3_and_dynamodb.sh
          ./create_s3_and_dynamodb.sh
      
      - name: Terragrunt Init
        run: |
          cd infrastructure/dev/vpc
          terragrunt init

      - name: Terragrunt Plan
        run: |
          cd infrastructure/dev/vpc
          terragrunt plan
      
      
