name: Deploy AWS infrastructure
on:
  workflow_dispatch:
    
permissions:
  id-token: write
  contents: read

jobs:
  deploy_infrastructure:
    name: Deploy Infrastructure
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Terragrunt
        run: |
          curl -LO https://github.com/gruntwork-io/terragrunt/releases/download/v0.48.1/terragrunt_linux_amd64
          sudo mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
          sudo chmod +x /usr/local/bin/terragrunt

      - name: Terraform Format Check
        run: terraform fmt -check -diff -recursive .

      - name: Terragrunt Format Check
        run: terragrunt hclfmt -check -diff -recursive .

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          audience: sts.amazonaws.com
          role-to-assume: ${{ vars.AWS_IAM_ROLE }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Terragrunt Validate
        run: terragrunt validate-all

      - name: Set up Git authentication for private modules
        run: |
          git config --global url."https://github.com/".insteadOf git@github.com:
          git config --global url."https://${{ secrets.GH_ACTION_TOKEN }}:@github.com/".insteadOf "https://github.com/"

      - name: Terragrunt Plan 
        run : |
          cd infrastructure/ 
          terragrunt run-all plan 
      
      - name: Terragrunt Apply 
        run: | 
          cd infrastructure/
          terragrunt run-all apply -auto-approve --terragrunt-non-interactive 

